### PR TITLE
Fix problems detected by @phpstan

### PR DESCRIPTION
**Pull request by szepeviktor**
@SerafimArts Please consider running `phpstan analyze src/ -l 5`

### CODE REVIEW

**Comment by SerafimArts** [comment]
Yes, it might be nice to add support for static analysis. Thx/

But I would suggest a vimeo/psalm, because its more powerful tool.

**Comment by szepeviktor** [comment]
All right.

We have different opinions then.

**Comment by ondrejmirtes** [comment]
@SerafimArts I see that you use `symfony/console`. PHPStan understands custom commands much better than Psalm. It knows what types can come from `$input->getOption()` - instead of the general `string|string[]|bool|null` typehint, it knows precisely what type you'll get :) (assuming you also install phpstan-symfony and configure it)

**Comment by SerafimArts** [comment]
@ondrejmirtes this is a dev dependency for subs generation: https://github.com/SerafimArts/Pipe/blob/master/resources/.phpstorm.autocomplete.php

And it is not part of the actual code used =)

With the same success, the symfony console can be replaced with a basic php script. Just the console command can be reused for your needs.

**Pull request merged**
